### ISSUE TITLE
Seven segment digits

### ISSUE THREAD

**Issue by josecfvalente** [kfrancis/ocr#8]
Hello kfrancis,

Congratulations on the excellent work you have done! I am trying to read digits from 7-segment digits, but so far, I haven’t achieved positive results. Is there a possibility to effectively read these digits?

I intend to develop a .NET MAUI app where the user can record the readings from a digital blood pressure monitor using the device's camera.

Thanks.

**Comment by kfrancis** [comment]
Unfortunately, since I'm using platform APIs here I don't get an opportunity to use a custom model. I would think, even though I had a hell of a time personally using Tesseract, that a custom model trained on 7-seg displays would work perfectly here. [Example](https://github.com/DevashishPrasad/LCD-OCR)

That being said, what I might try before giving up is processing the image a little to make it easier for the platform API to possibly get it correct. Maybe a color filter, since 7 segments are usually monochrome, then blur to try and fill in the gaps? The openCV in that example uses things like dilation and erosion to do that.

**Comment by josecfvalente** [comment]
I'll give it a try, thanks for the tips.
